#!/usr/bin/env bash
# //tools:convert_hf against a committed synthetic HuggingFace checkpoint.
#
# WHY THIS EXISTS. convert_hf is the path real GPT-2 weights come through, and it
# had ZERO test references. Its two load-bearing behaviours -- the Conv1D
# transpose and the 148/160 tensor reconciliation -- were covered only by
# downloading 522 MB, which no test does. Every claim in M-14 flows through this
# code.
#
# WHY A SYNTHETIC FIXTURE. The real file is 522 MB and uncommittable, and
# docs/engineering-lessons.md L11 forbids a wildcard test that needs an artifact
# a clean checkout does not have. tests/fixtures/hf_tiny is 12 KB, committed, and
# regenerated by scripts/gen_convert_fixture.py.
#
# WHY THE VALUES MATTER. Every 2-D weight in the fixture holds
# value[row][col] = row*1000 + col, so after conversion element [out][in] must be
# in*1000 + out. With random weights this test would pass whether or not the
# transpose happened -- which is the only bug it exists to catch.
set -uo pipefail

fail() { echo "FAIL: $*" >&2; exit 1; }

CONVERT="$TEST_SRCDIR/_main/tools/convert_hf"
FIX="$TEST_SRCDIR/_main/tests/fixtures/hf_tiny"
WORK="${TEST_TMPDIR:-/tmp}/convert_hf_test"
rm -rf "$WORK"; mkdir -p "$WORK"

[ -x "$CONVERT" ] || fail "convert_hf binary not found at $CONVERT"
[ -f "$FIX/model.safetensors" ] || fail "fixture missing at $FIX (run scripts/gen_convert_fixture.py)"

"$CONVERT" --model "$FIX/model.safetensors" --config "$FIX/config.json" \
           --out "$WORK/tiny.ckpt" > "$WORK/convert.log" 2>&1 \
  || fail "convert_hf failed: $(tail -3 "$WORK/convert.log")"

# The reconciliation is printed, so assert on it rather than trusting exit 0.
grep -q "mapped 28 parameters + 2 causal masks skipped = 30 (header has 30)" "$WORK/convert.log" \
  || fail "reconciliation line missing or wrong: $(grep mapped "$WORK/convert.log")"

python3 - "$WORK/tiny.ckpt" <<'PYEOF'
import struct, sys

C, V, P, L = 8, 17, 16, 2

raw = open(sys.argv[1], "rb").read()
assert len(raw) > 64, "checkpoint is header-only"
vals = struct.unpack(f"<{(len(raw) - 64) // 4}f", raw[64:])

# .bin order, the same correspondence tensors.hpp owns. Sizes are derived from
# the config rather than hard-coded totals, so a shape bug shows up as a length
# mismatch instead of silently shifting every later tensor.
sizes = [("wte", V * C), ("wpe", P * C), ("ln1w", L * C), ("ln1b", L * C),
         ("qkvw", L * 3 * C * C), ("qkvb", L * 3 * C), ("attprojw", L * C * C),
         ("attprojb", L * C), ("ln2w", L * C), ("ln2b", L * C),
         ("fcw", L * 4 * C * C), ("fcb", L * 4 * C), ("fcprojw", L * C * 4 * C),
         ("fcprojb", L * C), ("lnfw", C), ("lnfb", C)]
off, k = {}, 0
for n, s in sizes:
    off[n] = k
    k += s
assert k == len(vals), f"payload is {len(vals)} floats, the layout wants {k}"

def check_transposed(name, base, rows, cols):
    """cppgpt [rows, cols] came from HF [cols, rows] with value[r][c] = r*1000+c."""
    bad = []
    for o in range(rows):
        for i in range(cols):
            got, want = vals[base + o * cols + i], float(i * 1000 + o)
            if got != want:
                bad.append((o, i, got, want))
    assert not bad, (f"{name}: NOT transposed -- {len(bad)} elements wrong, "
                     f"first {bad[0]}. An untransposed read gives row*1000+col.")

# All four Conv1D tensors, both layers. Non-square shapes (3C, 4C) throughout, so
# a transpose that merely swaps two equal dimensions cannot pass.
for l in range(L):
    check_transposed(f"qkvw[{l}]", off["qkvw"] + l * 3 * C * C, 3 * C, C)
    check_transposed(f"attprojw[{l}]", off["attprojw"] + l * C * C, C, C)
    check_transposed(f"fcw[{l}]", off["fcw"] + l * 4 * C * C, 4 * C, C)
    check_transposed(f"fcprojw[{l}]", off["fcprojw"] + l * C * 4 * C, C, 4 * C)

# Non-transposed tensors must be carried through verbatim, or a blanket
# transpose would pass the checks above and corrupt these.
for r in range(V):
    for c in range(C):
        got, want = vals[off["wte"] + r * C + c], float(r * 1000 + c)
        assert got == want, f"wte[{r}][{c}] = {got}, want {want} (must NOT be transposed)"

print(f"  convert_hf: {len(vals)} params, 8 Conv1D tensors transposed, wte verbatim")
PYEOF
[ $? -eq 0 ] || fail "checkpoint contents are wrong"

# A file whose tensors do not reconcile must be REFUSED, not written. Truncating
# the header's tensor list is the cheapest way to produce one.
python3 - "$FIX/model.safetensors" "$WORK/broken.safetensors" <<'PYEOF'
import json, struct, sys
raw = open(sys.argv[1], "rb").read()
n = struct.unpack("<Q", raw[:8])[0]
hdr = json.loads(raw[8:8 + n])
hdr["h.0.attn.extra_unmapped"] = {"dtype": "F32", "shape": [1], "data_offsets": [0, 4]}
new = json.dumps(hdr, separators=(",", ":")).encode()
new += b" " * ((8 - len(new) % 8) % 8)
open(sys.argv[2], "wb").write(struct.pack("<Q", len(new)) + new + raw[8 + n:])
PYEOF
if "$CONVERT" --model "$WORK/broken.safetensors" --config "$FIX/config.json" \
              --out "$WORK/broken.ckpt" > "$WORK/broken.log" 2>&1; then
  fail "convert_hf accepted a file with an unaccounted-for tensor"
fi
grep -q "unaccounted for" "$WORK/broken.log" || fail "refusal did not say why"
[ ! -f "$WORK/broken.ckpt" ] || fail "convert_hf wrote a checkpoint it had refused"

echo "PASS: convert_hf transpose, reconciliation, and refusal"
