// M1 gate: cppgpt matches canonical GPT-2 in PyTorch, from identical weights.
//
// Loads tests/fixtures/gpt2_parity.bin (generated by scripts/gen_fixtures.py in the
// torch venv), copies PyTorch's exact initial weights into the model, and asserts:
//   * forward   — logits match to ≤ 1e-4,
//   * backward  — every gradient matches to ≤ 1e-3,
//   * training  — the loss after each of 10 AdamW steps matches to ≤ 1e-3.
// This is the strong proof: gradchecks show the backward is consistent with the
// forward; parity shows the forward *is* canonical GPT-2.
#include <cstdio>
#include <cstring>

#include "cppgpt/model.hpp"
#include "cppgpt/optimizer.hpp"
#include "cppgpt/verify.hpp"
#include "tests/check.hpp"

using namespace cppgpt;

int main() {
    const ParityFixture fx = load_parity_fixture("tests/fixtures/gpt2_parity.bin");
    GPT2 model(fx.cfg, fx.B, fx.T);
    CHECK(model.param_count() == fx.n_params);  // the param layouts agree

    const auto load_init = [&]() {
        std::memcpy(model.params().wte, fx.params.data(), fx.n_params * sizeof(float));
    };

    // ---- forward parity ----
    load_init();
    model.forward(fx.tokens.data(), fx.targets.data());
    const float logit_err = max_abs_diff(model.acts().logits, fx.logits.data(), fx.logits.size());
    CHECK(logit_err < 1e-4f);
    CHECK(std::fabs(model.mean_loss() - fx.losses[0]) < 1e-3f);

    // ---- backward parity ----
    model.zero_grads();
    model.backward(fx.tokens.data(), fx.targets.data());
    const float grad_err = max_abs_diff(model.grads().wte, fx.grads.data(), fx.n_params);
    CHECK(grad_err < 1e-3f);

    // ---- 10-step AdamW trajectory parity ----
    load_init();  // restore PyTorch's initial weights; moments are still fresh (no update() yet)
    const AdamW opt{.lr = 1e-2f};  // must match gen_fixtures.py LR
    float loss_err = 0.0f;
    for (int s = 0; s < fx.n_steps; ++s) {
        model.forward(fx.tokens.data(), fx.targets.data());
        loss_err = std::fmax(loss_err, std::fabs(model.mean_loss() - fx.losses[static_cast<std::size_t>(s)]));
        model.zero_grads();
        model.backward(fx.tokens.data(), fx.targets.data());
        model.update(opt);
    }
    CHECK(loss_err < 1e-3f);

    std::printf("parity: logit err %.2e (<1e-4), grad err %.2e (<1e-3), loss err %.2e (<1e-3)\n",
                static_cast<double>(logit_err), static_cast<double>(grad_err),
                static_cast<double>(loss_err));
    return cppgpt::test::summary();
}
