// Byte-level BPE: differential against two independent oracles.
//
// The gate is an EQUALITY on token streams, not a similarity score. A near-miss
// pre-tokenizer still produces fluent-looking output, so "close" would tell us
// nothing -- and the token ids ARE the model's interface, so a single wrong id
// indexes the wrong embedding row.
//
// tests/fixtures/bpe_gpt2.bin is generated by scripts/gen_bpe_fixture.py from
// tiktoken (OpenAI) AND transformers (HuggingFace), which share no code. The
// generator refuses to write a case the two disagree on, so the fixture is not
// one implementation's opinion.
#include "cppgpt/bpe.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

#include "tests/check.hpp"

using namespace cppgpt;

namespace {
std::string slurp(const char* p) {
    std::ifstream f(p, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}
}  // namespace

int main() {
    auto r = BpeTokenizer::open("tests/fixtures/gpt2/vocab.json", "tests/fixtures/gpt2/merges.txt");
    CHECK(r.has_value());
    if (!r) return cppgpt::test::summary();
    const BpeTokenizer& t = *r;

    CHECK(t.vocab_size() == 50257);
    CHECK(t.eot_id() == 50256);

    const std::string fx = slurp("tests/fixtures/bpe_gpt2.bin");
    CHECK(fx.size() > 8);
    if (fx.size() <= 8) return cppgpt::test::summary();

    std::size_t p = 0;
    const auto u32 = [&]() { std::uint32_t v; std::memcpy(&v, fx.data() + p, 4); p += 4; return v; };
    const auto i32 = [&]() { std::int32_t v; std::memcpy(&v, fx.data() + p, 4); p += 4; return v; };
    CHECK(u32() == 0x42504531u);  // "BPE1"
    const std::uint32_t n_cases = u32();
    CHECK(n_cases > 0);

    int encode_mismatch = 0, decode_mismatch = 0, cases = 0, tokens = 0;
    for (std::uint32_t c = 0; c < n_cases; ++c) {
        const std::uint32_t tlen = u32();
        const std::string text(fx.data() + p, tlen);
        p += tlen;
        const std::uint32_t nid = u32();
        std::vector<int> want(nid);
        for (std::uint32_t k = 0; k < nid; ++k) want[k] = i32();

        bool ok = false;
        const std::vector<int> got = t.encode(text, &ok);
        ++cases;
        tokens += static_cast<int>(want.size());
        if (!ok || got != want) {
            if (encode_mismatch < 3) {
                std::fprintf(stderr, "  encode mismatch on %s%.40s%s\n  want:",
                             "\"", text.c_str(), "\"");
                for (const int x : want) std::fprintf(stderr, " %d", x);
                std::fprintf(stderr, "\n  got :");
                for (const int x : got) std::fprintf(stderr, " %d", x);
                std::fprintf(stderr, "%s\n", ok ? "" : "  (encode reported failure)");
            }
            ++encode_mismatch;
        }
        // Round-trip on the ORACLE's ids, so decode is tested independently of
        // whether encode agreed.
        if (t.decode(want) != text) ++decode_mismatch;
    }
    std::printf("  %d cases, %d tokens: %d encode mismatches, %d decode mismatches\n",
                cases, tokens, encode_mismatch, decode_mismatch);
    CHECK(encode_mismatch == 0);
    CHECK(decode_mismatch == 0);

    // Non-ASCII must FAIL LOUDLY rather than mis-split. Silently producing
    // plausible tokens for text this pre-tokenizer cannot handle is the one
    // outcome worse than refusing.
    {
        bool ok = true;
        (void)t.encode("café", &ok);
        CHECK(!ok);
        bool ok2 = false;
        (void)t.encode("plain ascii", &ok2);
        CHECK(ok2);
    }
    return cppgpt::test::summary();
}
